version: '3'

services:
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - './nuxt:/app'
      - './app/node_modules/'
    command: [ "npm", "run", "dev" ]
    environment:
      - CHOKIDAR_USEPOLLING=true

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.dev
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel

  nginx:
    image: nginx:1.20
    container_name: dln-nginx
    volumes:
      - ./laravel:/var/www/laravel
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf