version: '3'

services:
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    command: [ "npm", "run", "dev" ]
    volumes:
      - './nuxt:/app'
      - '/app/node_modules/'
    environment:
      - CHOKIDAR_USEPOLLING=true

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.dev
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel

  maria_db:
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./laravel/storage/dbdata:/var/lib/mysql
    networks:
      - docker-laravel-nuxt

  nginx:
    image: nginx:1.20
    container_name: dln-nginx
    volumes:
      - ./laravel:/var/www/laravel
      - ./settings/nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf